'use server';

import { GoogleGenAI } from '@google/genai';
import { prisma } from '@life-track/db';
import { auth } from '@/auth';
import { revalidatePath } from 'next/cache';
import { getAffiliateLink } from '@/lib/affiliates';
import { extractJsonFromResponse } from '@/lib/ai-parser';

function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY || '';
  if (!apiKey) {
    throw new Error(
      'Clé API Gemini non configurée (variable GEMINI_API_KEY manquante dans Vercel/.env).',
    );
  }
  return new GoogleGenAI({ apiKey });
}

export async function runSmartAudit(language: string = 'fr') {
  try {
    const session = await auth();

    if (!session?.user?.id) {
      throw new Error('Non autorisé');
    }

    const userId = session.user.id;

    const ninetyDaysAgo = new Date();
    ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);

    const expenses = await prisma.expense.findMany({
      where: { userId: userId, date: { gte: ninetyDaysAgo } },
      orderBy: { date: 'desc' },
    });

    const LANG_PROMPTS: Record<
      string,
      {
        langName: string;
        defaultTitle: string;
        notEnoughData: string;
        jsonError: string;
      }
    > = {
      fr: {
        langName: 'Français',
        defaultTitle: 'Conseil IA',
        notEnoughData:
          'Pas assez de données (minimum 3 dépenses sur 90 jours requises).',
        jsonError: "Erreur lors du traitement du JSON généré par l'IA.",
      },
      en: {
        langName: 'English',
        defaultTitle: 'AI Insight',
        notEnoughData:
          'Not enough data (minimum 3 expenses over 90 days required).',
        jsonError: 'Error processing JSON generated by AI.',
      },
      de: {
        langName: 'Deutsch',
        defaultTitle: 'KI-Ratschlag',
        notEnoughData:
          'Nicht genügend Daten (mindestens 3 Ausgaben in 90 Tagen erforderlich).',
        jsonError: 'Fehler beim Verarbeiten des von der KI generierten JSON.',
      },
      es: {
        langName: 'Español',
        defaultTitle: 'Consejo IA',
        notEnoughData:
          'Insuficientes datos (mínimo 3 gastos en 90 días requeridos).',
        jsonError: 'Error al procesar el JSON generado por la IA.',
      },
      pt: {
        langName: 'Português',
        defaultTitle: 'Conselho IA',
        notEnoughData:
          'Dados insuficientes (mínimo de 3 despesas em 90 dias necessárias).',
        jsonError: 'Erro ao processar o JSON gerado pela IA.',
      },
    };

    const config = LANG_PROMPTS[language] || LANG_PROMPTS.fr;

    if (expenses.length < 3) {
      return { success: false, message: config.notEnoughData };
    }

    const prompt = `Analyze these expenses: ${JSON.stringify(expenses)}. 
Identify saving opportunities and anomalies.
IMPORTANT: Write all titles and descriptions in ${config.langName}.

PRIORITY RULE: Select up to 5 events with the highest financial impact:
1. Exceptionally high single expenses.
2. Recurring bills where savings are possible.

Generate a JSON array of up to 5 objects:
[{ 
  "type": "SAVING" | "INFO", 
  "title": string, 
  "description": string, 
  "potentialSaving": number,
  "category": "ENERGY" | "TELECOM" | "INSURANCE" | "BANK" | "OTHER"
}]

Reply only with valid JSON.`;

    const ai = getGeminiClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const responseText = response.text || '';
    const insights = extractJsonFromResponse(responseText);

    if (!insights || !Array.isArray(insights)) {
      return { success: false, message: config.jsonError };
    }

    await prisma.insight.deleteMany({ where: { userId: userId } });

    const insightPromises = insights.map((insight) => {
      const linkSource =
        insight.category || `${insight.title} ${insight.description}`;
      const link =
        insight.type === 'SAVING' ? getAffiliateLink(linkSource) : null;

      return prisma.insight.create({
        data: {
          userId: userId,
          type: insight.type || 'INFO',
          title: insight.title || config.defaultTitle,
          description: insight.description || '',
          potentialSaving:
            typeof insight.potentialSaving === 'number'
              ? insight.potentialSaving
              : null,
          affiliateUrl: link,
        },
      });
    });

    await Promise.all(insightPromises);

    revalidatePath('/dashboard');
    return { success: true, message: 'audit_success' };
  } catch (error) {
    console.error('Erreur audit IA Gemini:', error);
    const rawMessage = error instanceof Error ? error.message : String(error);

    if (
      rawMessage.includes('401') ||
      rawMessage.includes('API_KEY_INVALID') ||
      rawMessage.includes('Unauthorized')
    ) {
      return {
        message:
          'Clé API Gemini invalide. Vérifiez votre variable GEMINI_API_KEY sur Vercel/.env.',
      };
    }

    if (
      rawMessage.includes('429') ||
      rawMessage.includes('RESOURCE_EXHAUSTED')
    ) {
      return {
        message:
          "Quota d'appels Gemini dépassé. Veuillez patienter une minute.",
      };
    }

    return {
      message:
        rawMessage || 'Désolé, le coach IA est indisponible pour le moment.',
    };
  }
}

// Fallback par règles locales si l'IA est indisponible ou hors quota
function getLocalFallbackCategory(title: string): string {
  const t = title.toLowerCase();
  if (
    t.includes('loyer') ||
    t.includes('rent') ||
    t.includes('immo') ||
    t.includes('housing')
  ) {
    return 'LOGEMENT';
  }
  if (
    t.includes('edf') ||
    t.includes('engie') ||
    t.includes('totalenergies') ||
    t.includes('electricité') ||
    t.includes('gaz') ||
    t.includes('energy')
  ) {
    return 'ENERGIE';
  }
  if (
    t.includes('carrefour') ||
    t.includes('auchan') ||
    t.includes('leclerc') ||
    t.includes('lidl') ||
    t.includes('starbucks') ||
    t.includes('uber eats') ||
    t.includes('restaurant') ||
    t.includes('food') ||
    t.includes('monoprix') ||
    t.includes('coffee')
  ) {
    return 'ALIMENTATION';
  }
  if (
    t.includes('uber') ||
    t.includes('sncf') ||
    t.includes('ratp') ||
    t.includes('total') ||
    t.includes('essence') ||
    t.includes('train') ||
    t.includes('taxi') ||
    t.includes('flight') ||
    t.includes('airline')
  ) {
    return 'TRANSPORT';
  }
  if (
    t.includes('netflix') ||
    t.includes('spotify') ||
    t.includes('apple') ||
    t.includes('prime') ||
    t.includes('free mobile') ||
    t.includes('orange') ||
    t.includes('sfr') ||
    t.includes('bouygues') ||
    t.includes('subscription')
  ) {
    return 'ABONNEMENTS';
  }
  if (
    t.includes('cinema') ||
    t.includes('ugc') ||
    t.includes('pathe') ||
    t.includes('theatre') ||
    t.includes('concert') ||
    t.includes('steam') ||
    t.includes('playstation') ||
    t.includes('sparkfun')
  ) {
    return 'LOISIRS';
  }
  if (
    t.includes('pharma') ||
    t.includes('doctolib') ||
    t.includes('medecin') ||
    t.includes('hopital') ||
    t.includes('dentiste') ||
    t.includes('health')
  ) {
    return 'SANTE';
  }
  return 'AUTRE';
}

export async function categorizeTransactions(titles: string[]) {
  if (!titles || titles.length === 0) return {};

  try {
    const ai = getGeminiClient();

    const prompt = `Classifie rigoureusement ces libellés bancaires : ${JSON.stringify(
      titles,
    )}.
Pour chaque libellé, attribue l'une de ces 8 catégories obligatoires :
- LOGEMENT (loyer, charges, agence)
- ENERGIE (électricité, gaz, eau)
- ALIMENTATION (supermarchés, restaurants, boulangerie, café, Uber Eats)
- TRANSPORT (essence, péage, train, métro, taxi, Uber, bus)
- ABONNEMENTS (forfait internet, téléphone, streaming Netflix/Spotify/Apple/Amazon)
- LOISIRS (cinéma, jeux, sorties, musées, loisirs créatifs)
- SANTE (pharmacie, médecin, optique, dentiste)
- AUTRE (retraits distributeurs ou inclassables)

Réponds STRICTEMENT sous forme d'objet JSON associatif : {"Libellé exact": "CATEGORIE"}`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const responseText = response.text || '';
    const parsed = extractJsonFromResponse(responseText) || {};

    const result: Record<string, string> = {};
    for (const title of titles) {
      result[title] = parsed[title] || getLocalFallbackCategory(title);
    }
    return result;
  } catch (error) {
    console.warn(
      'IA indisponible pour la catégorisation, bascule sur le fallback local:',
      error,
    );
    const fallback: Record<string, string> = {};
    for (const title of titles) {
      fallback[title] = getLocalFallbackCategory(title);
    }
    return fallback;
  }
}
