'use server';

import { GoogleGenAI } from '@google/genai';
import { prisma } from '@life-track/db';
import { auth } from '@/auth';
import { revalidatePath } from 'next/cache';
import { getAffiliateLink } from '@/lib/affiliates';
import { extractJsonFromResponse } from '@/lib/ai-parser';

function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY || '';
  if (!apiKey) {
    throw new Error(
      'Clé API Gemini non configurée (variable GEMINI_API_KEY manquante dans Vercel/.env).',
    );
  }
  return new GoogleGenAI({ apiKey });
}

export async function runSmartAudit(language: string = 'fr') {
  try {
    const session = await auth();

    if (!session?.user?.id) {
      throw new Error('Non autorisé');
    }

    const userId = session.user.id;

    const ninetyDaysAgo = new Date();
    ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);

    const expenses = await prisma.expense.findMany({
      where: { userId: userId, date: { gte: ninetyDaysAgo } },
      orderBy: { date: 'desc' },
    });

    const LANG_PROMPTS: Record<
      string,
      {
        langName: string;
        defaultTitle: string;
        notEnoughData: string;
        jsonError: string;
      }
    > = {
      fr: {
        langName: 'Français',
        defaultTitle: 'Conseil IA',
        notEnoughData:
          'Pas assez de données (minimum 3 dépenses sur 90 jours requises).',
        jsonError: "Erreur lors du traitement du JSON généré par l'IA.",
      },
      en: {
        langName: 'English',
        defaultTitle: 'AI Insight',
        notEnoughData:
          'Not enough data (minimum 3 expenses over 90 days required).',
        jsonError: 'Error processing JSON generated by AI.',
      },
      de: {
        langName: 'Deutsch',
        defaultTitle: 'KI-Ratschlag',
        notEnoughData:
          'Nicht genügend Daten (mindestens 3 Ausgaben in 90 Tagen erforderlich).',
        jsonError: 'Fehler beim Verarbeiten des von der KI generierten JSON.',
      },
      es: {
        langName: 'Español',
        defaultTitle: 'Consejo IA',
        notEnoughData:
          'Insuficientes datos (mínimo 3 gastos en 90 días requeridos).',
        jsonError: 'Error al procesar el JSON generado por la IA.',
      },
      pt: {
        langName: 'Português',
        defaultTitle: 'Conselho IA',
        notEnoughData:
          'Dados insuficientes (mínimo de 3 despesas em 90 dias necessárias).',
        jsonError: 'Erro ao processar o JSON gerado pela IA.',
      },
    };

    const config = LANG_PROMPTS[language] || LANG_PROMPTS.fr;

    if (expenses.length < 3) {
      return { success: false, message: config.notEnoughData };
    }

    const prompt = `Analyze these expenses: ${JSON.stringify(expenses)}. 
Identify saving opportunities and anomalies.
IMPORTANT: Write all titles and descriptions in ${config.langName}.

PRIORITY RULE: Select up to 5 events with the highest financial impact:
1. Exceptionally high single expenses.
2. Recurring bills where savings are possible.

Generate a JSON array of up to 5 objects:
[{ 
  "type": "SAVING" | "INFO", 
  "title": string, 
  "description": string, 
  "potentialSaving": number,
  "category": "ENERGY" | "TELECOM" | "INSURANCE" | "BANK" | "OTHER"
}]

Reply only with valid JSON.`;

    const ai = getGeminiClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const responseText = response.text || '';
    const insights = extractJsonFromResponse(responseText);

    if (!insights || !Array.isArray(insights)) {
      return { success: false, message: config.jsonError };
    }

    await prisma.insight.deleteMany({ where: { userId: userId } });

    const insightPromises = insights.map((insight) => {
      const linkSource =
        insight.category || `${insight.title} ${insight.description}`;
      const link =
        insight.type === 'SAVING' ? getAffiliateLink(linkSource) : null;

      return prisma.insight.create({
        data: {
          userId: userId,
          type: insight.type || 'INFO',
          title: insight.title || config.defaultTitle,
          description: insight.description || '',
          potentialSaving:
            typeof insight.potentialSaving === 'number'
              ? insight.potentialSaving
              : null,
          affiliateUrl: link,
        },
      });
    });

    await Promise.all(insightPromises);

    revalidatePath('/dashboard');
    return { success: true, message: 'audit_success' };
  } catch (error) {
    console.error('Erreur audit IA Gemini:', error);
    const rawMessage = error instanceof Error ? error.message : String(error);

    if (
      rawMessage.includes('401') ||
      rawMessage.includes('API_KEY_INVALID') ||
      rawMessage.includes('Unauthorized')
    ) {
      return {
        message:
          'Clé API Gemini invalide. Vérifiez votre variable GEMINI_API_KEY sur Vercel/.env.',
      };
    }

    if (rawMessage.includes('429') || rawMessage.includes('RESOURCE_EXHAUSTED')) {
      return {
        message:
          "Quota d'appels Gemini dépassé. Veuillez patienter une minute.",
      };
    }

    return {
      message:
        rawMessage || 'Désolé, le coach IA est indisponible pour le moment.',
    };
  }
}

export async function categorizeTransactions(titles: string[]) {
  try {
    const ai = getGeminiClient();

    const prompt = `Classe ces libellés de transactions bancaires : ${JSON.stringify(titles)}. 
Réponds en JSON uniquement sous forme d'objet associatif clé-valeur: {"Libellé exact": "CATEGORIE"}. 
Catégories autorisées exclusivement : LOGEMENT, ENERGIE, ALIMENTATION, TRANSPORT, ABONNEMENTS, LOISIRS, SANTE, AUTRE.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const responseText = response.text || '';
    return extractJsonFromResponse(responseText) || {};
  } catch (error) {
    console.error('Erreur catégorisation IA Gemini:', error);
    return {};
  }
}