'use server';

import { Mistral } from '@mistralai/mistralai';
import { prisma } from '@life-track/db';
import { auth } from '@/auth';
import { revalidatePath } from 'next/cache';
import { getAffiliateLink } from '@/lib/affiliates';
import { extractJsonFromResponse } from '@/lib/ai-parser';

function getMistralClient() {
  const apiKey = process.env.MISTRAL_API_KEY || '';
  if (!apiKey) {
    throw new Error(
      'Clé API Mistral non configurée (variable MISTRAL_API_KEY manquante dans Vercel/.env).'
    );
  }
  return new Mistral({ apiKey });
}

export async function runSmartAudit(language: string = 'fr') {
  try {
    const session = await auth();

    if (!session?.user?.id) {
      throw new Error('Non autorisé');
    }

    const userId = session.user.id;

    const ninetyDaysAgo = new Date();
    ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);

    const expenses = await prisma.expense.findMany({
      where: { userId: userId, date: { gte: ninetyDaysAgo } },
      orderBy: { date: 'desc' },
    });

    const LANG_PROMPTS: Record<
      string,
      {
        langName: string;
        legalNote: string;
        defaultTitle: string;
        notEnoughData: string;
        jsonError: string;
      }
    > = {
      fr: {
        langName: 'Français',
        legalNote:
          ' (Note : Cette estimation informative ne constitue pas un conseil financier personnalisé).',
        defaultTitle: 'Conseil IA',
        notEnoughData:
          'Pas assez de données (minimum 3 dépenses sur 90 jours requises).',
        jsonError: "Erreur lors du traitement du JSON généré par l'IA Mistral.",
      },
      en: {
        langName: 'English',
        legalNote:
          ' (Note: This informative estimate does not constitute personalized financial advice).',
        defaultTitle: 'AI Insight',
        notEnoughData:
          'Not enough data (minimum 3 expenses over 90 days required).',
        jsonError: 'Error processing JSON generated by Mistral AI.',
      },
      de: {
        langName: 'Deutsch',
        legalNote:
          ' (Hinweis: Diese Information stellt keine finanzielle Beratung dar).',
        defaultTitle: 'KI-Ratschlag',
        notEnoughData:
          'Nicht genügend Daten (mindestens 3 Ausgaben in 90 Tagen erforderlich).',
        jsonError: 'Fehler beim Verarbeiten des von Mistral AI generierten JSON.',
      },
      es: {
        langName: 'Español',
        legalNote:
          ' (Nota: Esta estimación informativa no constituye un consejo financiero personalizado).',
        defaultTitle: 'Consejo IA',
        notEnoughData:
          'Insuficientes datos (mínimo 3 gastos en 90 días requeridos).',
        jsonError: 'Error al procesar el JSON generado por Mistral AI.',
      },
      pt: {
        langName: 'Português',
        legalNote:
          ' (Nota: Esta estimativa informativa não constitui aconselhamento financeiro personalizado).',
        defaultTitle: 'Conselho IA',
        notEnoughData:
          'Dados insuficientes (mínimo de 3 despesas em 90 dias necessárias).',
        jsonError: 'Erro ao processar o JSON gerado pela Mistral AI.',
      },
    };

    const config = LANG_PROMPTS[language] || LANG_PROMPTS.fr;

    if (expenses.length < 3) {
      return { success: false, message: config.notEnoughData };
    }

    const prompt = `Analyze these expenses: ${JSON.stringify(expenses)}. 
Identify saving opportunities and anomalies.
IMPORTANT: Write all titles and descriptions in ${config.langName}.

PRIORITY RULE: Select up to 5 events with the highest financial impact:
1. Exceptionally high single expenses.
2. Recurring bills where savings are possible.

Generate a JSON array of up to 5 objects:
[{ 
  "type": "SAVING" | "INFO", 
  "title": string, 
  "description": string, 
  "potentialSaving": number,
  "category": "ENERGY" | "TELECOM" | "INSURANCE" | "BANK" | "OTHER"
}]

Reply only with valid JSON.`;

    const client = getMistralClient();
    const chatResponse = await client.chat.complete({
      model: 'mistral-small-latest',
      messages: [{ role: 'user', content: prompt }],
    });

    const rawContent = chatResponse.choices?.[0]?.message?.content;
    const responseText =
      typeof rawContent === 'string'
        ? rawContent
        : String(rawContent || '');

    const insights = extractJsonFromResponse(responseText);
    if (!insights || !Array.isArray(insights)) {
      return { success: false, message: config.jsonError };
    }

    await prisma.insight.deleteMany({ where: { userId: userId } });

    const insightPromises = insights.map((insight) => {
      const linkSource =
        insight.category || `${insight.title} ${insight.description}`;
      const link =
        insight.type === 'SAVING' ? getAffiliateLink(linkSource) : null;

      return prisma.insight.create({
        data: {
          userId: userId,
          type: insight.type || 'INFO',
          title: insight.title || config.defaultTitle,
          description: (insight.description || '') + config.legalNote,
          potentialSaving:
            typeof insight.potentialSaving === 'number'
              ? insight.potentialSaving
              : null,
          affiliateUrl: link,
        },
      });
    });

    await Promise.all(insightPromises);

    revalidatePath('/dashboard');
    return { success: true, message: 'audit_success' };
  } catch (error) {
    console.error('Erreur audit IA Mistral:', error);
    const rawMessage = error instanceof Error ? error.message : String(error);
    
    if (rawMessage.includes('401') || rawMessage.includes('Unauthorized') || rawMessage.includes('invalid_api_key')) {
      return {
        message: 'Clé API Mistral invalide (Erreur 401). Vérifiez votre variable MISTRAL_API_KEY sur Vercel.',
      };
    }

    if (rawMessage.includes('429') || rawMessage.includes('Rate limit')) {
      return {
        message: 'Quota d\'appels Mistral dépassé (Erreur 429). Veuillez patienter quelques minutes.',
      };
    }

    return {
      message: rawMessage || 'Désolé, le coach IA est indisponible pour le moment.',
    };
  }
}

export async function categorizeTransactions(titles: string[]) {
  try {
    const client = getMistralClient();

    const prompt = `Classe ces libellés : ${JSON.stringify(titles)}. 
Réponds en JSON uniquement : {"Libellé": "CATEGORIE"}. 
Catégories : LOGEMENT, ENERGIE, ALIMENTATION, TRANSPORT, ABONNEMENTS, LOISIRS, SANTE, AUTRE.`;

    const chatResponse = await client.chat.complete({
      model: 'mistral-small-latest',
      messages: [{ role: 'user', content: prompt }],
    });

    const rawContent = chatResponse.choices?.[0]?.message?.content;
    const responseText = typeof rawContent === 'string' ? rawContent : String(rawContent || '');

    return extractJsonFromResponse(responseText) || {};
  } catch (error) {
    console.error('Erreur catégorisation IA Mistral:', error);
    return {};
  }
}
